
services:
###> shopware/core ###
  database:
    image: mysql:8.3.0-oracle
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-shopware}
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-shopware}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    volumes:
       - ./docker/db/data:/var/lib/mysql:rw
###< shopware/core ###
